### ISSUE TITLE
去掉标签，完善日期选择组件

### ISSUE THREAD

**Issue by scottliyq** [joyplus/o2oadmin#129]
![image](https://cloud.githubusercontent.com/assets/1333896/10630283/5bfdcb3c-7808-11e5-9ba2-273accdc05c0.png)
![image](https://cloud.githubusercontent.com/assets/1333896/10630331/7a042eaa-7808-11e5-9f33-9da481da1681.png)

**Comment by onealtang** [comment]
fixed by #133

**Comment by onealtang** [comment]
done
